name: go_minyan
description: Making easy to find minyan

version: 3.2.0+46

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Firestore
  cloud_firestore: 0.13.0+1
  cloud_functions: ^0.4.1+8
  firebase_auth: ^0.14.0+1
  firebase_messaging: 5.1.4
  #firebase_core: ^0.4.0

  #Location & Maps
  geolocator: ^5.1.3
  google_maps_flutter: ^0.5.20+6
  location : ^2.3.0
  flutter_localizations:
    sdk: flutter

  #Multiple FAB
  flutter_speed_dial: ^1.2.1

  #Bloc pattern
  flutter_bloc: ^0.20.0
  equatable: ^0.2.0

  #meta: ^1.1.6

  #Custom Alerts
  rflutter_alert:
    git: git://github.com/RatelHub/rflutter_alert.git

  #Save data on device
  shared_preferences: ^0.5.6+1

  #Push notification
  flutter_local_notifications: ^0.9.1

  #Send Mail
  mailer: ^3.0.2
  url_launcher: ^5.4.1

  fluttertoast: ^3.1.3

  #Theme changer
  provider:

  #Permission
  #permission_handler: ^3.3.0
  permission_handler: 4.2.0+hotfix.2
  connectivity: ^0.4.6+2

#  http: ^0.12.0+2
#  flutter_compass: ^0.2.0
#  sensors: ^0.4.0+1
#  flare_flutter: ^1.5.5
#  location: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^8.0.1

  #Language
  intl_translation: ^0.17.6

  #Change app icon
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  image_path_ios: "assets/img/icon.png"
  image_path_android: "assets/img/icon.png"
  android: true
  ios: true
flutter:


  uses-material-design: true

  assets:
    - assets/img/pinMap.png
    - assets/img/star.png
    - assets/img/background.jpg
    - assets/img/logo.png
    - assets/img/icon.png

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf